name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Fork Repository
      uses: actions/checkout@v2
      with:
        ref: master  # 更改为你要同步的分支名
        persist-credentials: false

    - name: Set up Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git remote add upstream https://github.com/imsyy/DailyHot.git
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

    - name: Fetch Upstream Changes
      run: git fetch upstream

    - name: Sync with Upstream
      run: |
        git checkout master  # 请确保这里的分支名称与上面一致
        git merge upstream/master --allow-unrelated-histories --no-commit || true
        git restore --source=HEAD --staged --worktree .github/workflows/sync-fork.yml
        git add .  # 解决冲突并添加所有文件
        git commit -m 'Sync with upstream' || echo 'No changes to commit'
        git push origin master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
